###
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "anusha",
  "name": "Anusha Bandari",
  "password": "anusha_0610",
  "gender": "female",
  "location": "Huzurabad"
}

###
POST http://localhost:3000/login/

{
  "username": "anusha",
  "password": "anusha_0610"
}

